name: 'Update Github Project fields'
description: 'This action updates custom fields in a GitHub Project.'
author: "Fellowmind Fabric Solutions"
branding:
  icon: 'edit'
  color: 'black'
runs:
  using: 'composite'
  steps:
    - name: Find custom fields in project
      shell: bash
      run: gh project field-list --format json --owner ${{ inputs.project-owner }} -q '.name == "${{ inputs.field-name }}"' ${{ inputs.project-number }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      
inputs:
  github-token:
    description: 'The Github token to use.'
    required: true
  project-owner:
    description: 'The project owner.'
    required: true
  project-number:
    description: 'The project number.'
    required: true
  field-name:
    description: "The field to update"
    required: true
  field-value:
    description: "The value to write to the field"
    required: true
    