name: 'Update Github Project fields'
description: 'This action updates custom fields in a GitHub Project.'
author: "Fellowmind Fabric Solutions"
branding:
  icon: 'edit'
  color: 'black'
runs:
  using: 'composite'
  steps:
    - id: custom-field-key-id
      name: Find custom field key id
      shell: bash
      run: gh project field-list --format json --owner ${{ inputs.project-owner }} --jq '.fields.[] | select(.name == "${{ inputs.field-name }}") | .id' ${{ inputs.project-number }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - id: custom-field-value-id
      name: Find custom fields value id
      shell: bash
      run: gh project field-list --format json --owner ${{ inputs.project-owner }} --jq '.fields.[] | select(.name == "${{ inputs.field-name }}") | .options.[] |  select(.name == "${{ inputs.field-value }}") | .id' ${{ inputs.project-number }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - id: update-issue
      name: Update custom field for issue
      shell: bash
      run: gh project --owner ${{ inputs.project-owner }} --id ${{ inputs.issue }} --field-id ${{ inputs.custom-field-key-id }} --single-select-option-id ${{ outputs.custom-field-value-id }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    
inputs:
  github-token:
    description: 'The Github token to use.'
    required: true
  project-owner:
    description: 'The project owner.'
    required: true
  project-number:
    description: 'The project number.'
    required: true
  field-name:
    description: "The field to update"
    required: true
  field-value:
    description: "The value to write to the field"
    required: true
  issue:
    description: "The issue to update"
    required: true
    