name: 'Update Github Project fields'
description: 'This action updates custom fields in a GitHub Project.'
author: "Fellowmind Fabric Solutions"
branding:
  icon: 'edit'
  color: 'black'
runs:
  using: 'composite'
  steps:
    - id: project-id
      name: Find the project id
      shell: bash
      run: gh project list --format json --owner ${{ inputs.project-owner }} --jq '"project=" + (.projects.[] | select(.number == ${{ inputs.project-number }}).id)' ${{ inputs.project-number }}  >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - id: issue-id
      name: Find the issue id
      shell: bash
      run: gh project item-list --format json --owner ${{ inputs.project-owner }} -L 50000 --jq '"issue=" + (.items.[] | select(.content.url == "${{ github.event.issue.html_url }}").id)' ${{ inputs.project-number }}  >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - id: field-id
      name: Find custom field id
      shell: bash
      run: gh project field-list --format json --owner ${{ inputs.project-owner }} --jq '"field=" + (.fields.[] | select(.name == "${{ inputs.field-name }}") | .id)' ${{ inputs.project-number }}  >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - id: option-id
      name: Find custom fields value id
      shell: bash
      run: gh project field-list --format json --owner ${{ inputs.project-owner }} --jq '"option=" + (.fields.[] | select(.name == "${{ inputs.field-name }}") | .options.[] |  select(.name == "${{ inputs.field-value }}") | .id)' ${{ inputs.project-number }} >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - id: update-issue
      name: Update custom field for issue
      shell: bash
      run: gh project item-edit --project-id ${{ steps.project-id.outputs.project }} --id ${{ steps.issue-id.outputs.issue }} --field-id ${{ steps.field-id.outputs.field }} --single-select-option-id ${{ steps.option-id.outputs.option }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    
inputs:
  github-token:
    description: 'The Github token to use.'
    required: true
  project-owner:
    description: 'The project owner.'
    required: true
  project-number:
    description: 'The project number.'
    required: true
  field-name:
    description: "The field to update"
    required: true
  field-value:
    description: "The value to write to the field"
    required: true
